name: EdoriaSkyblock
version: 1.0.0
author: Nistro
description: Skyblock plugin for Edoria server.
main: fr.nistro.edoriaskyblock.Main
api: INVALID
depend: [Vault, PlaceholderAPI]

commands:
    edoriaSkyblock:
        description: Commande principale du plugin EdoriaSkyblock
        usage: /edoriaSkyblock
        aliases: [edoriaSkyblock, esb]
    testWebhook:
        description: Test Discord command
        usage: /edoriaSkyblock testDiscord
        aliases: []